name: x86

on: [push, pull_request]

jobs:
  build_x86:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        build_type: [Debug, Release]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      BUILD_TYPE: ${{matrix.build_type}}
    steps:
      - name: Git clone repository
        uses: actions/checkout@v2
      - name: Building
        run: bash ./compile.sh $BUILD_TYPE
      - name: Testing
        run: bash ./test.sh
